### ISSUE TITLE
0.3.1 is not available via Cocoapods central trunk

### ISSUE THREAD

**Issue by piercifani** [Anviking/Decodable#24]

**Comment by mhuusko5** [comment]
Neither is (now) 0.3.2

**Comment by Anviking** [comment]
I have never used Cocoapods, so I'm not sure if I want to be maintaining the Cocoapods central thing. I didn't create it – *"Fabric"* did. Which I think means that @ohwutup has been maintaining it, since he's the one who has been updating the podspec and the the one who created it in the first place (#15). (btw, @ohwutup thanks!)

**Comment by ohwutup** [comment]
I can make this happen for sure

**Comment by ohwutup** [comment]
@Anviking you should be able to close this. just pushed 0.3.2 to CocoaPods
