### ISSUE TITLE
Keep Podspec up to date/pushed to CocoaPods

### ISSUE THREAD

**Issue by mhuusko5** [Anviking/Decodable#48]
Currently the podspec in the repo supports OS X, but isn't pushed to cocoapods.
Also theres been a lot of good work on master the last couple months, but no new tags, podspec updates/pushes.

I'm very much invested in the growth/up-to-dateness of Decodable, and would be happy to maintain the podspec, if added as a maintainer.

Thanks

**Comment by Anviking** [comment]
Thanks, didn't realize how many things was added after `v0.3.2`. I was dragging on releasing a new version because of having to update the readme, so that was the problem, not keeping the podspec up to date. Thanks for your offer though! And issues like these or PRs are of course always welcome. :smile: 

Just released 0.3.3, which should be pushed to CocoaPods soon.

**Comment by ohwutup** [comment]
hey @mhuusko5 ! just updated that cocoapod! go ahead and give it a shot!

**Comment by mhuusko5** [comment]
Awesome, thanks! Will do
