### ISSUE TITLE
Operators that return T? should return nil when the key path is missing

### ISSUE THREAD

**Issue by brentleyjones** [Anviking/Decodable#61]
Currently the `=>` operators that return `T?`, `[T]?`, etc. will throw a `.MissingKey` if the key path is missing. For JSON not having a field be available is usually the same as having it explicitly be `null`. Right now the documentation suggests `try?` for cases like this, but then you will swallow `.TypeMismatch` errors.

I recommend that either the `=>` operators that return a `nil` also do so on `.MissingKey`, or a new set of operators, such as `=>?`, be introduced. The type already states that it's valid for it to not exist (the point of an `Optional` in my mind) and `.MissingKey` matches that.

**Comment by JaviSoto** [comment]
I agree. This can be accomplished with `try? j => "key"`, but it seems like if the property that you're binding that to is optional, that should be the default behavior.

Re `=>?`: IIRC this used to exist, and then went away. I think the downside if similar to `try?`: you have to remember, whereas marking the member as optional should I think be enough.

**Comment by brentleyjones** [comment]
The main issue with `try?` is that it eats up `.TypeMismatch` and any future error types that may be introduced. I think it just being the default behavior of `=>` when the property is optional. `.MissingKey` is very very similar to `NSNull`.

**Comment by Anviking** [comment]
I am reluctant changing the `=>`. If the API always returns null instead of leaving the field out, which is what the API of Github and Twitter (looking at it briefly) does (at least often), a missing key means that something is wrong. Ether you are getting an unexpected response format or you have misspelled a key in the mapping. That could cause confusion debugging, especially without excessive-covering tests and with a field that is null/missing 99% of the time.

API that treat `.MissingKey` as `null` (haven't actually seen any, but have little experience) and different response formats are of course valid concerns, totally agree.

And almost love the idea of bringing back `=>?`. In addition to not-throwing-on-`.TypeMismatch` it is also syntactically more convenient than `try?`. `try? j => "key"` is a bit longer, but `(try? j => "key") ?? "default"` is even more cumbersome.

**Comment by brentleyjones** [comment]
I can concede to not wanting to change `=>`. At the last two companies (enterprises) I've worked at they don't return fields when they are null, thus my request. I'm perfectly fine with `=>?` though!
