### ISSUE TITLE
Getting a "ResponseObject"

### ISSUE THREAD

**Issue by damianesteban** [Anviking/Decodable#62]
This library is great, I've been using it with some of my structs and it I dig it.  How can I use this to return "JSON Objects", i.e. a raw JSON object?

**Comment by Anviking** [comment]
Sorry, how do you mean? Encoding?

**Comment by damianesteban** [comment]
I'm sorry, yes.  I was referring to the encoding.

**Comment by Anviking** [comment]
For small usage I would have just:
```swift
extension Foo: Encodable {
    func encode() -> NSDictionary {
        return ["a" : a, "b": b.encode()]
    }
}
```

Otherwise, if you want to encode every field in the struct [JohnSundell/Wrap](https://github.com/JohnSundell/Wrap) might be useful. And if you really really want encoding/decoding mapping to be declared in the same place, and to be the same, (and don't care about having `var`s with default values etc), [LoganWright/Genome](https://github.com/LoganWright/Genome) appears to do that.

**Comment by damianesteban** [comment]
Thank you.  I wasn't familiar with [JohnSundell/Wrap](https://github.com/JohnSundell/Wrap) or [LoganWright/Genome](https://github.com/LoganWright/Genome), excellent suggestions.
