### ISSUE TITLE
Nested key tests are failing in Swift 3.0

### ISSUE THREAD

**Issue by Anviking** [Anviking/Decodable#94]
Nested keys don't work `j => "a" => "b" => "c"`
Workaround: 
```swift
json => ["a", "b", "c"]
```
Have still not investigated closely (option click for these overloads fails for me) but suspect there is some kind of `String` and `AnyObject` overload ambiguity.

**Comment by voidref** [comment]
Ok, so I looked into this, it turns out that they must have changed the order in which things are evaluated.

The test firs invokes `=> (lhs: String, rhs:String) -> [String]` with the result of `["owner", "oops"]`, and then calls into `=> <A: Decodable>(json: AnyObject, path: [String])throws-> A` with `"repo"` as `json` and the above result as the path.

Perhaps there is an operator precedence value that can be set to solve this...

**Comment by Anviking** [comment]
Hm, so that should be because `String` is `Decodable`. Should be fixed by #77 then, having another non-decodable type as keys.
